# Generated by Django 3.2.9 on 2021-11-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_num', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('room_type', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField(default=0)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('email', models.CharField(default=' ', max_length=100)),
                ('phone_num', models.IntegerField(default=0)),
                ('encrypt_pwd', models.CharField(default=' ', max_length=50)),
                ('rooms', models.CharField(default=' ', max_length=150)),
            ],
        ),
    ]
