# Generated by Django 3.2.9 on 2021-11-22 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
