# Generated by Django 3.2.9 on 2021-11-25 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0002_auto_20211122_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=10),
        ),
    ]
