# Generated by Django 3.2.9 on 2021-11-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0002_auto_20211122_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_num',
        ),
        migrations.AlterField(
            model_name='user',
            name='rooms',
            field=models.CharField(default='{}', max_length=150),
        ),
    ]
