# Generated by Django 3.2.7 on 2021-11-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0003_auto_20211127_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pottygarbage',
            field=models.CharField(default='potty', max_length=100),
        ),
    ]
