# Generated by Django 3.2.7 on 2021-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagement', '0004_user_pottygarbage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_num',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='room_num',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pottygarbage',
        ),
        migrations.AddField(
            model_name='room',
            name='customer_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=1234, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room_booked',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
